var signUp= helpers.id("signup");
var login= helpers.id("login");
var splashDiv = helpers.id("splash");
var formDiv = helpers.id("formDiv");
var app = helpers.id("app");
var appBOdy = helpers.id("appBody");
var appMessage = helpers.id("appMessage");
var mesage = helpers.id("message");
var openRequest = indexedDB.open("wrinq", 1);
var database;
