var signUp= helpers.id("signup");
var login= helpers.id("login");
var splashDiv = helpers.id("splash");
var formDiv = helpers.id("formDiv");
var messageDiv = helpers.id("messageDiv");
var app = helpers.id("app");
var appMessage = helpers.id("appMessage");
var mesage = helpers.id("message");
var openRequest = indexedDB.open("wrinq", 1);
var database;
